### ISSUE TITLE
Fabric loader 0.11.x support?

### ISSUE THREAD

**Issue by Youmiel** [adryd325/chat-lag-fix#3]
This mod could only be loaded with fabric-loader 0.12.0+, but in metadata its dependency includes  "fabricloader": ">=0.11.3", which is not accurate. 

By the way, some 1.16.5 mods (at least those I'm using) are out-of-date and don't support fabric-loader 0.12.x, updating to 0.12.x will cause lots of errors that I'm not able to handle.

Error log:
```
2022-01-10 12:24:47,991 main ERROR Error processing element Queue ([Appenders: null]): CLASS_NOT_FOUND
2022-01-10 12:24:48,001 main WARN JNDI lookup class is not available because this JRE does not support JNDI. JNDI string lookups will not be available, continuing configuration. Ignoring java.lang.ClassCastException: class org.apache.logging.log4j.core.lookup.JndiLookup
[12:24:48] [main/INFO]: Loading for game Minecraft 1.16.5
[12:24:48] [main/INFO]: [FabricLoader] Loading 4 mods:
	- chatlagfix@2.0.2
	- fabricloader@0.11.7
	- java@11
	- minecraft@1.16.5
[12:24:48] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/D:/%e6%b8%b8%e6%88%8f/MC/TestEnv/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
Exception in thread "main" java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'chatlagfix'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:143)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/loader/impl/util/UrlConversionException
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:191)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 3 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.impl.util.UrlConversionException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 12 more
```

**Comment by adryd325** [comment]
I've uploaded a version compatible with minimum 0.11.3 to modrinth

**Comment by Felix14-v2** [comment]
@adryd325 , it seems still not working for 1.17.1 version.

<details>
 <summary>Logs (nothing interesting here)</summary>

```
[12:44:03] [main/INFO]: Loading for game Minecraft 1.17.1
[12:44:03] [main/INFO]: [FabricLoader] Loading 9 mods:
	- chatlagfix@2.0.2
	- fabric-api-base@0.3.0+a02b44633d
	- fabric-resource-loader-v0@0.4.7+b7ab61213d
	- fabric-screen-api-v1@1.0.4+198a96213d
	- fabricloader@0.11.7
	- java@17
	- lazydfu@0.1.2
	- minecraft@1.17.1
	- modmenu@2.0.14
[12:44:03] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/%d0%90%d0%bb%d0%b5%d0%ba%d1%81%d0%b0%d0%bd%d0%b4%d1%80/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[12:44:03] [main/INFO]: Compatibility level set to JAVA_16
```

</details>

I can't use Fabric Loader 0.12.x because my modpack founded on [ThatOrThis](https://github.com/EZForever/ThatOrThis), which still doesn't work on it. 😔

**Comment by adryd325** [comment]
The bug is fixed on mojangs side so its not necesary anymore, but i've uploaded the newest version to modrinth

**Comment by Felix14-v2** [comment]
> The bug is fixed on mojangs side

Lol, this bug is still happening to me (without your mod). Anyway, thank you!
